# Generated by Django 6.0.5 on 2026-06-02 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldo_por_hora', models.DecimalField(decimal_places=2, default=10.0, help_text='Sueldo base por hora en euros', max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('descripcion', models.TextField(blank=True)),
                ('lugar', models.CharField(max_length=200)),
                ('descanso_comida', models.BooleanField(default=False, help_text='Si está marcado se restará 1h de comida')),
                ('sueldo_por_hora', models.DecimalField(decimal_places=2, help_text='Sueldo por hora aplicado a este registro', max_digits=6)),
                ('duracion_total', models.DurationField(editable=False)),
                ('duracion_trabajada', models.DurationField(editable=False)),
                ('sueldo_registro', models.DecimalField(decimal_places=2, editable=False, help_text='Importe ganado en este registro', max_digits=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-hora_entrada'],
            },
        ),
    ]
